from dotenv import load_dotenv
import os

load_dotenv()

COSMOS_ENDPOINT = os.getenv("COSMOS_ENDPOINT")
COSMOS_KEY = os.getenv("COSMOS_KEY")

PATIENT_DB_NAME = os.getenv("PATIENT_DB_NAME")
PATIENT_CONTAINER = os.getenv("PATIENT_CONTAINER")

TRANSCRIPT_DB_NAME = os.getenv("TRANSCRIPT_DB_NAME")
TRANSCRIPT_CONTAINER = os.getenv("TRANSCRIPT_CONTAINER")

APPOINTMENT_DB_NAME = os.getenv("APPOINTMENT_DB_NAME")
APPOINTMENT_CONTAINER = os.getenv("APPOINTMENT_CONTAINER")

AZURE_OPEN_AI_ENDPOINT = os.getenv("AZURE_OPEN_AI_ENDPOINT")
AZURE_OPEN_AI_API_KEY = os.getenv("AZURE_OPEN_AI_API_KEY")
AZURE_OPENAI_MODEL = os.getenv("AZURE_OPENAI_MODEL")